CREATE TABLE grss_order(
	id VARCHAR(36) NOT NULL COMMENT '订单ID',
	NAME VARCHAR(50) NOT NULL COMMENT '订单名称',
	amount VARCHAR(10) NOT NULL COMMENT '订单金额',
	coach_id VARCHAR(36) NOT NULL COMMENT '教练ID',
	user_id VARCHAR(36) NOT NULL COMMENT '学员用户ID',
	pay_date DATETIME COMMENT '付款日期',
	state INT(1) NOT NULL DEFAULT 0 COMMENT '0:下单未支付,1下单未完成,2完成订单',
	order_date DATETIME NOT NULL COMMENT '下单日期',
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '订单';
CREATE TABLE grss_video_category(
	id VARCHAR(36) NOT NULL COMMENT '视频分类ID',
	NAME VARCHAR(100) NOT NULL COMMENT '视频分类名称',
	prarent_id VARCHAR(36) NOT NULL DEFAULT '0' COMMENT '父节点ID',
	cate_code VARCHAR(50) NOT NULL COMMENT '分类编码 C001 一级分类, C001001 二级分类 依次列推',
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '视频分类';
CREATE TABLE grss_vido(
	id VARCHAR(36) NOT NULL COMMENT '视频ID',
	NAME VARCHAR(200) NOT NULL COMMENT '视频名称',
	url VARCHAR(300) NOT NULL COMMENT '视频播放地址',
	upload_date DATETIME NOT NULL COMMENT '上传视频日期',
	update_date DATETIME  COMMENT '修改视频日期',
	cat_id VARCHAR(36) NOT NULL COMMENT '视频分类ID',
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '视频库';
CREATE TABLE grss_user_accounts(
	id VARCHAR(36) NOT NULL COMMENT '用户账户ID',
	card_no VARCHAR(25) NOT NULL COMMENT '银行卡号',
	open_account_name VARCHAR(5) NOT NULL COMMENT '开户人姓名',
	open_account_bank VARCHAR(10) NOT NULL COMMENT '开户银行',
	open_account_city VARCHAR(50) NOT NULL COMMENT '开户省市',
	user_id VARCHAR(36) NOT NULL COMMENT '用户ID',
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '用户账户';
DROP TABLE coach_type;
CREATE TABLE grss_coach_type(
	id INT(11) NOT NULL AUTO_INCREMENT COMMENT '教练类型ID',
	NAME VARCHAR(50) NOT NULL COMMENT '类型名称',
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '教练类型';
CREATE TABLE grss_user_setup(
	id INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户设置ID',
	reply INT(1) NOT NULL DEFAULT 1 COMMENT '回复我的 1允许 0不允许',
	praise INT(1) NOT NULL DEFAULT 1 COMMENT '赞 1允许 0不允许',
	private_chat INT(1) NOT NULL DEFAULT 1 COMMENT '私聊 1允许 0不允许',
	new_fans INT(1) NOT NULL DEFAULT 1 COMMENT '新粉丝 1允许 0不允许',
	system_message INT(1) NOT NULL DEFAULT 1 COMMENT '系统消息 1允许 0不允许',
	user_id VARCHAR(36) NOT NULL COMMENT '用户ID',
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '用户设置';
CREATE TABLE verify_code(
	phone VARCHAR(11) NOT NULL COMMENT '手机号',
	`code` VARCHAR(6) NOT NULL COMMENT '验证码',
	send_date INT(13) NOT NULL COMMENT '发送验证码时间',
	PRIMARY KEY(phone)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '发送验证码';